# typed: false
# frozen_string_literal: true

# The Clidable desktop app. Separate from the `clidable` formula on purpose:
# that name is the CLI on every platform, and `brew install …/clidable` must not
# drag a GUI onto a headless box. Installing both is fine — the app carries its
# own server, and the CLI's `clidable open` hands folders to it.
#
# Generated by scripts/render-brew-packaging.ts — do not hand-edit hashes.
cask "clidable-desktop" do
  arch arm: "aarch64", intel: "x64"

  version "0.1.1"
  sha256 arm:   "ce2a277029ace5ac64fbabdb9a53d3f482b260b41e425e430140a6b55b8ebfca",
         intel: "f6cf4a5c2cee1df97a5f8ca945049b9ea48797bd04653494d2fa6e5f32ee8891"

  url "https://github.com/openclide/clidable/releases/download/v#{version}/Clidable_#{version}_#{arch}.dmg",
      verified: "github.com/openclide/clidable/"
  name "Clidable"
  desc "GUI for CLI coding agents"
  homepage "https://github.com/openclide/clidable"

  app "Clidable.app"

  # The app's documented behaviour is window-close-hides / tray-Quit-stops, so it
  # is normally RUNNING. Without this, uninstall deletes Clidable.app out from
  # under a live process, leaving an orphaned server on :7878 and no tray icon
  # left to quit it.
  uninstall quit: "dev.clidable.app"

  # Mirrors the env-paths layout the app actually writes (see
  # docs/configuration.md — data, cache and logs are deliberately separate so
  # OS backup tools treat them differently).
  zap trash: [
    "~/Library/Application Support/Clidable",
    "~/Library/Caches/Clidable",
    "~/Library/Logs/Clidable",
    "~/Library/Preferences/dev.clidable.app.plist",
    "~/Library/Saved Application State/dev.clidable.app.savedState",
    # Tauri's WKWebView writes both of these; without them `--zap` leaves the
    # webview's storage behind and doesn't actually return the machine to clean.
    "~/Library/WebKit/dev.clidable.app",
    "~/Library/HTTPStorages/dev.clidable.app",
  ]
end
