# typed: false
# frozen_string_literal: true

# The Clidable desktop app. Separate from the `clidable` formula on purpose:
# that name is the CLI on every platform, and `brew install …/clidable` must not
# drag a GUI onto a headless box. Installing both is fine — the app carries its
# own server, and the CLI's `clidable open` hands folders to it.
#
# Generated by scripts/render-brew-packaging.ts — do not hand-edit hashes.
cask "clidable-desktop" do
  arch arm: "aarch64", intel: "x64"

  version "0.1.2"
  sha256 arm:   "e089813018fa7d214412885de831a04bf640fd5df8d2f236b16da32eec9ae078",
         intel: "18bd495b88165046f8d6389be072ad544c4d8972ea92e29319a9ec3f2f2cb224"

  url "https://github.com/openclide/clidable/releases/download/v#{version}/Clidable_#{version}_#{arch}.dmg",
      verified: "github.com/openclide/clidable/"
  name "Clidable"
  desc "GUI for CLI coding agents"
  homepage "https://github.com/openclide/clidable"

  app "Clidable.app"

  # The app's documented behaviour is window-close-hides / tray-Quit-stops, so it
  # is normally RUNNING. Without this, uninstall deletes Clidable.app out from
  # under a live process, leaving an orphaned server on :7878 and no tray icon
  # left to quit it.
  uninstall quit: "dev.clidable.app"

  # Mirrors the env-paths layout the app actually writes (see
  # docs/configuration.md — data, cache and logs are deliberately separate so
  # OS backup tools treat them differently).
  zap trash: [
    "~/Library/Application Support/Clidable",
    "~/Library/Caches/Clidable",
    "~/Library/Logs/Clidable",
    "~/Library/Preferences/dev.clidable.app.plist",
    "~/Library/Saved Application State/dev.clidable.app.savedState",
    # Tauri's WKWebView writes both of these; without them `--zap` leaves the
    # webview's storage behind and doesn't actually return the machine to clean.
    "~/Library/WebKit/dev.clidable.app",
    "~/Library/HTTPStorages/dev.clidable.app",
  ]
end
