# typed: false
# frozen_string_literal: true

# The Clidable server/CLI. The download artifact is named `clidable-server-*`
# (kept distinct from the `Clidable_*` desktop installers in the release
# listing), but the installed command is `clidable`. This formula owns the
# bare name so `brew install openclide/tap/clidable` means the CLI on every
# platform; the desktop app ships separately as the `clidable-desktop` cask.
#
# Generated by scripts/render-brew-packaging.ts — do not hand-edit hashes.
class Clidable < Formula
  desc "GUI for CLI coding agents — server and CLI"
  homepage "https://github.com/openclide/clidable"
  version "0.1.3"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/openclide/clidable/releases/download/v0.1.3/clidable-server-darwin-arm64"
      sha256 "e9edb3649aba36de96f21b2f0dd7afb08750751bcf16f22a0c89bf500e9f2782"
    end
    on_intel do
      url "https://github.com/openclide/clidable/releases/download/v0.1.3/clidable-server-darwin-x64"
      sha256 "76850f0150f1874790bf753f44e235a3e5c8608ba02c6b8254f7ffc41cb28b06"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/openclide/clidable/releases/download/v0.1.3/clidable-server-linux-arm64"
      sha256 "01b20a79dc79206d1c61527f7f741d82dfda2d9835f34009421bbe3805ee1ddf"
    end
    on_intel do
      url "https://github.com/openclide/clidable/releases/download/v0.1.3/clidable-server-linux-x64"
      sha256 "2666c1834f2c921e6df5ae422120768a28917b0f9dc4759ccf515ee18719aa97"
    end
  end

  def install
    # Download artifact is clidable-server-<os>-<arch>; the command is `clidable`.
    bin.install Dir["clidable-server-*"].first => "clidable"
  end

  test do
    assert_path_exists bin/"clidable"
    assert_predicate bin/"clidable", :executable?
    # RUN it: existence + the executable bit both pass for a wrong-arch or
    # truncated download, which is precisely the failure a checksum can't catch
    # (a re-uploaded asset hashes fine and still won't exec). `--version` prints
    # the bare version and exits 0.
    assert_equal version.to_s, shell_output("#{bin}/clidable --version").strip
  end
end
