# typed: false
# frozen_string_literal: true

# The Clidable server/CLI. The download artifact is named `clidable-server-*`
# (kept distinct from the `Clidable_*` desktop installers in the release
# listing), but the installed command is `clidable`. This formula owns the
# bare name so `brew install openclide/tap/clidable` means the CLI on every
# platform; the desktop app ships separately as the `clidable-desktop` cask.
#
# Generated by scripts/render-brew-packaging.ts — do not hand-edit hashes.
class Clidable < Formula
  desc "GUI for CLI coding agents — server and CLI"
  homepage "https://github.com/openclide/clidable"
  version "0.1.2"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/openclide/clidable/releases/download/v0.1.2/clidable-server-darwin-arm64"
      sha256 "0c73fd0f12ba97b8a26258c7ba003087de03fef8b943cca5388a19c1c060e68b"
    end
    on_intel do
      url "https://github.com/openclide/clidable/releases/download/v0.1.2/clidable-server-darwin-x64"
      sha256 "085285f9aec7ba5a8f90787ac4f403e1f7cd3c9416ae667ae47dbc68e33dfe5e"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/openclide/clidable/releases/download/v0.1.2/clidable-server-linux-arm64"
      sha256 "0dc1e7e3ee20149432c0d773d442c0e2ee0a024d02439d8fe9c3312486820225"
    end
    on_intel do
      url "https://github.com/openclide/clidable/releases/download/v0.1.2/clidable-server-linux-x64"
      sha256 "ec230e583ed20890e18ea2bb4958194bd28884171e66adb56dc190b715ef918d"
    end
  end

  def install
    # Download artifact is clidable-server-<os>-<arch>; the command is `clidable`.
    bin.install Dir["clidable-server-*"].first => "clidable"
  end

  test do
    assert_path_exists bin/"clidable"
    assert_predicate bin/"clidable", :executable?
    # RUN it: existence + the executable bit both pass for a wrong-arch or
    # truncated download, which is precisely the failure a checksum can't catch
    # (a re-uploaded asset hashes fine and still won't exec). `--version` prints
    # the bare version and exits 0.
    assert_equal version.to_s, shell_output("#{bin}/clidable --version").strip
  end
end
