# typed: false
# frozen_string_literal: true

# The Clidable server/CLI. The download artifact is named `clidable-server-*`
# (kept distinct from the `Clidable_*` desktop installers in the release
# listing), but the installed command is `clidable`. This formula owns the
# bare name so `brew install openclide/tap/clidable` means the CLI on every
# platform; the desktop app ships separately as the `clidable-desktop` cask.
#
# Generated by scripts/render-brew-packaging.ts — do not hand-edit hashes.
class Clidable < Formula
  desc "GUI for CLI coding agents — server and CLI"
  homepage "https://github.com/openclide/clidable"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/openclide/clidable/releases/download/v0.1.1/clidable-server-darwin-arm64"
      sha256 "96e1b20b0b855a6f303c2e1401393535dfd4ce6e4cfc3f4b73d63a4a4ee953d8"
    end
    on_intel do
      url "https://github.com/openclide/clidable/releases/download/v0.1.1/clidable-server-darwin-x64"
      sha256 "d6b3e0095e6ca4f46bd6c1eae897742f445ab6d7767bc7e67095a2f95968e08f"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/openclide/clidable/releases/download/v0.1.1/clidable-server-linux-arm64"
      sha256 "17525c244503b3d586f4b55e3e3761ce85c3269c22c3a135836a6a51150e7723"
    end
    on_intel do
      url "https://github.com/openclide/clidable/releases/download/v0.1.1/clidable-server-linux-x64"
      sha256 "c8c3d3ce156b5feb62b075f2bd41c18bec5cd5273379e2225ee4f7f3b6f77538"
    end
  end

  def install
    # Download artifact is clidable-server-<os>-<arch>; the command is `clidable`.
    bin.install Dir["clidable-server-*"].first => "clidable"
  end

  test do
    assert_path_exists bin/"clidable"
    assert_predicate bin/"clidable", :executable?
    # RUN it: existence + the executable bit both pass for a wrong-arch or
    # truncated download, which is precisely the failure a checksum can't catch
    # (a re-uploaded asset hashes fine and still won't exec). `--version` prints
    # the bare version and exits 0.
    assert_equal version.to_s, shell_output("#{bin}/clidable --version").strip
  end
end
